# Generated by Django 3.0.2 on 2020-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NER_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.FileField(null=True, upload_to='C:\\Users\\larissa pinto\\Desktop\\ner\\media')),
            ],
        ),
    ]
