# Generated by Django 3.0.2 on 2020-03-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200317_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ner_form',
            name='txt',
            field=models.FileField(null=True, upload_to='C:\\Users\\larissa pinto\\Desktop\\ner\\media'),
        ),
    ]
