# Generated by Django 3.0.2 on 2020-03-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
