# Generated by Django 3.0.2 on 2020-03-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NER_Form',
        ),
    ]
